from turtle import *#it is a python library which is used for drawing
# pentagon
pencolor('red')
speed("slowest")
fillcolor("purple")
pensize("10")
begin_fill()
forward(100)
right(72)
forward(100)
right(72)
forward(100)
right(72)
forward(100)
right(72)
forward(100)
right(72)
end_fill()
mainloop()